name: emailSender
on:
  workflow_dispatch:
    
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Setup python env"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'